#!/bin/bash

DISCO=$1

echo
echo "Particionamiento"
echo


sudo fdisk /dev/$DISCO << EOF
n
p
1

+1G
n
e



n

+1G
n

+1G
n

+1G
n

+1G
n

+1G
n

+1G
n

+1G
n

+1G
n

+900M
w
EOF

echo
echo "muestra particionamiento"
echo

sudo fdisk /dev/sde -l



sudo mkfs.ext4 /dev/sde
sudo mkfs.ext4 /dev/sde1
sudo mkfs.ext4 /dev/sde10
sudo mkfs.ext4 /dev/sde11
sudo mkfs.ext4 /dev/sde12
sudo mkfs.ext4 /dev/sde13
sudo mkfs.ext4 /dev/sde5
sudo mkfs.ext4 /dev/sde6
sudo mkfs.ext4 /dev/sde7
sudo mkfs.ext4 /dev/sde8
sudo mkfs.ext4 /dev/sde9


echo
echo "formateo a ext4"
echo
sudo lsblk /dev/sde -f | grep -i "sde" | awk '{printf("Disco %s: Formato: %s \n",$1,$2)}' | tail -n +2


echo
echo "Montaje"
echo 
